### ISSUE TITLE
Mining station Refinery (Rockstation, z5)

### ISSUE THREAD

**Issue by LZakida** [addictgamer/Terrastation-13#30]
The forge/refinery/whateverhaveyou on the mining station does not work. I don't know why but I'm not particularly interested (yet) in fixing this as there is an ore redeemer that does it as well and gives you points and shit for doing so. Still, there are a small handful of things one might want to use it for and at the moment it's just junk. This same idea can probably be applied to the (shittier) one on Geostation as well.

**Comment by LZakida** [comment]
This issue was fixed as of commit e5fd997849b3f3c2dea279165f21a1ad34188616 (I think). I only just remembered I opened an issue about this in the past.

**Comment by taukausanake** [comment]
Can we please start using Pull Requests? We'll never know when an issue is fixed otherwise

**Comment by LZakida** [comment]
what is a pull request and how do I fuck its butthole

**Comment by addictgamer** [comment]
@taukausanake A more formal development process would be nice, but seeing as there's really only one active developer currently (part-time at that), I haven't cared enough to say anything.

**Comment by taukausanake** [comment]
I'm not developing on it mainly because fuck this repo (but if PRs are used I might reconsider) and I too am quite busy with things like doing actual programming for class. Also still being a little bitch about Rockstation but that's been accounted for. I do have a bunch of things I need to change from vanilla paracode saved in a list but only after classes are done.

Eh, I'll more likely do my edits on my own side and then see if I can move them over here or merge somehow afterwards.

**Comment by addictgamer** [comment]
You are welcome to submit your own pull requests.
